### PR TITLE
Update method signature to be Laravel 5.3 compatible

### PR DESCRIPTION
**Pull request by alariva**
Fixes https://github.com/Snowfire/Beautymail/issues/46

```
> php artisan optimize
PHP Fatal error:  Declaration of Snowfire\Beautymail\Beautymail::send() must be compatible with Illuminate\Contracts\Mail\Mailer::send($view, array $data = Array, $callback = NULL) in /.../app/vendor/snowfire/beautymail/src/Snowfire/Beautymail/Beautymail.php on line 8
                                                                                                                                                                      
  [Symfony\Component\Debug\Exception\FatalErrorException]                                                                                                             
  Declaration of Snowfire\Beautymail\Beautymail::send() must be compatible with Illuminate\Contracts\Mail\Mailer::send($view, array $data = Array, $callback = NULL)  

Script php artisan optimize handling the post-update-cmd event returned with an error
```

### CODE REVIEW

**Comment by Luceos** [comment]
@emilsundberg can't currently properly use this, because no version was tagged. Either I use dev-master or the specific commit has. Could you do something about that :pray:

**Comment by emilsundberg** [comment]
@Luceos Done 😃

**Comment by Luceos** [comment]
Is it just me or is there no new tag? @emilsundberg :smirk:

**Comment by emilsundberg** [comment]
https://github.com/Snowfire/Beautymail/releases/tag/v1.0.12

**Pull request merged**
