### PR TITLE
Blade "or" operator remove in Laravel 5.7 for null coalesce

### PR DESCRIPTION
**Pull request by MoT3rror**

### CODE REVIEW

**Comment by emilsundberg** [comment]
Thanks for your PR. I'd suggest we switch to using isset/if instead of the null coalescing operator. That way we can keep this working for people still using PHP 5.x

**Comment by emilsundberg** [comment]
See #95

**Comment by MoT3rror** [comment]
No problem on that. Just a heads up Laravel 5.7 is using PHP 7.1.3 or higher. If this issue comes up, they should be past 5.x a long time ago.

**Comment by emilsundberg** [comment]
Yes, but there is a lot of people using older Laravel with older PHP which now can use the latest version of this package :)

**Pull request closed without merging**
